### ISSUE TITLE
Playlists con carecteres latinos

### ISSUE THREAD

**Issue by Kenzitron** [vmunozre/SpotifyDownloader#1]
Debe haber un problema a la hora de procesar playlists con caracteres como la ñ o las tildes, no permite importar la lista.

**Comment by vmunozre** [comment]
Buenas, en principio hay algunos caracteres que dan problema, tenemos intención de resolverlo antes de la _versión final_. Muchas gracias por el aviso! A ver si este verano podemos sacar una versión final!
